### PR TITLE
eclipse oxygen + maven build + eclipse plugins + webeditor + update doc

### PR DESCRIPTION
**Pull request by r4mtor**
- updated some chapter in the documentation
 - added a whole example of maven structured xtext example
 - added a runtime-EclipseXtext project to have some examples to play

### CODE REVIEW

**Comment by r4mtor** [comment]
todo description of the new abstractformatter2

**Comment by goto40** [comment]
I merge the document. The next step for me is to transform the document to a md file or similar, because it seems easier to me to check the differences that way...

**Comment by r4mtor** [comment]
If you replace the odt files with a markdown, I could write chapter for the new formatter if you want

**Comment by goto40** [comment]
I started with Latex, since I think it will be easier to fix specific
formatting issues... Not sure.

2018-06-12 21:53 GMT+02:00 r4mtor <notifications@github.com>:

**Comment by goto40** [comment]
Is it ok for you if I add your Name to the autors?

2018-06-12 22:46 GMT+02:00 Pierre Bayerl <pierre.bayerl@googlemail.com>:

**Pull request merged**
